4.14.2

diff --git a/docker/init b/docker/init
--- a/docker/init
+++ b/docker/init
@@ -36,8 +36,13 @@ fi
 /usr/sbin/service postfix start
 
 # Initialize and update database (if needed)
-/bin/su -s /bin/bash -c "/usr/bin/php $WWW_DIR/tools/database/initialize.php" www-data
+/bin/su -s /bin/bash -c "/usr/bin/php $WWW_DIR/tools/database/initialize.php" www-data &&
 /bin/su -s /bin/bash -c "/usr/bin/php $WWW_DIR/tools/database/update.php" www-data
+
+if [ $? -ne 0 ];then
+    echo "Database initialization failed"
+    exit 1
+fi
 
 # Start shell service in background
 /bin/bash "$WWW_DIR/bin/service" &
