5.9.0

diff --git a/.github/workflows/test-api.yml b/.github/workflows/test-api.yml
--- a/.github/workflows/test-api.yml
+++ b/.github/workflows/test-api.yml
@@ -14,7 +14,7 @@ jobs:
       contents: read
     steps:
       - name: Checkout
-        uses: actions/checkout@v4
+        uses: actions/checkout@v6
 
       - name: Install curl
         run: sudo apt-get install curl jq wget -y
@@ -38,6 +38,9 @@ jobs:
               echo "API is not unreachable"
               exit 1
           fi
+
+      - name: Generate a random number to avoid conflicts when multiple pipelines run at the same time
+        run: echo "RANDOM=$(date +%s)" >> $GITHUB_ENV
 
       #
       # Download rpm and deb packages from https://packages.repomanager.net that will be used for upload testing
@@ -86,11 +89,10 @@ jobs:
       # Generate a unique package name to avoid conflicts when multiple pipelines run at the same time
       - name: (admin) Try to upload a deb package with an admin API key
         run: |
-          RANDOM=$(date +%s)
-          PACKAGE_NAME="${RANDOM}-${HOSTNAME}-admin_nginx_1.26.0-1~bookworm_amd64.deb"
+          PACKAGE_NAME="${{ env.RANDOM }}-${HOSTNAME}-admin_nginx_1.26.0-1~bookworm_amd64.deb"
 
           cp ${HOSTNAME}_nginx_1.26.0-1~bookworm_amd64.deb $PACKAGE_NAME
-          curl --fail-with-body -L --post301 -s -q -X POST -H "Authorization: Bearer ${{ secrets.API_TEST_ADMIN_API_KEY }}" -F "files=@${PACKAGE_NAME}" ${{ secrets.API_TEST_HOST }}/api/v2/snapshot/1/upload
+          curl --fail-with-body -L --post301 -s -q -X POST -H "Authorization: Bearer ${{ secrets.API_TEST_ADMIN_API_KEY }}" -F "file=@${PACKAGE_NAME}" ${{ secrets.API_TEST_HOST }}/api/v2/snapshot/1/upload
           if [ $? -ne 0 ]; then
               echo "Failed to upload deb package"
               exit 1
@@ -98,15 +100,41 @@ jobs:
 
       # Upload a rpm package using the admin API key
       # Generate a unique package name to avoid conflicts when multiple pipelines run at the same time
-      - name: (admin) Try to upload an rpm package with an admin API key
+      - name: (admin) Try to upload a rpm package with an admin API key
         run: |
-          RANDOM=$(date +%s)
-          PACKAGE_NAME="${RANDOM}-${HOSTNAME}-admin_nginx-1.26.0-1.el7.ngx.x86_64.rpm"
+          PACKAGE_NAME="${{ env.RANDOM }}-${HOSTNAME}-admin_nginx-1.26.0-1.el7.ngx.x86_64.rpm"
   
           cp ${HOSTNAME}_nginx-1.26.0-1.el7.ngx.x86_64.rpm $PACKAGE_NAME
-          curl --fail-with-body -L --post301 -s -q -X POST -H "Authorization: Bearer ${{ secrets.API_TEST_ADMIN_API_KEY }}" -F "files=@${PACKAGE_NAME}" ${{ secrets.API_TEST_HOST }}/api/v2/snapshot/2/upload
+          curl --fail-with-body -L --post301 -s -q -X POST -H "Authorization: Bearer ${{ secrets.API_TEST_ADMIN_API_KEY }}" -F "file=@${PACKAGE_NAME}" ${{ secrets.API_TEST_HOST }}/api/v2/snapshot/2/upload
           if [ $? -ne 0 ]; then
               echo "Failed to upload rpm package"
+              exit 1
+          fi
+
+      # Try to upload again the same deb package without overwrite flag, it should fail
+      - name: (admin) Try to upload the same deb package again with overwrite=false
+        run: |
+          PACKAGE_NAME="${{ env.RANDOM }}-${HOSTNAME}-admin_nginx_1.26.0-1~bookworm_amd64.deb"
+
+          cp ${HOSTNAME}_nginx_1.26.0-1~bookworm_amd64.deb $PACKAGE_NAME
+          OUTPUT=$(curl --fail-with-body -L --post301 -s -q -X POST -H "Authorization: Bearer ${{ secrets.API_TEST_ADMIN_API_KEY }}" -F "file=@${PACKAGE_NAME}" -F "overwrite=false" ${{ secrets.API_TEST_HOST }}/api/v2/snapshot/1/upload) || true
+    
+          if echo "$OUTPUT" | grep -q "Following packages already exist and have not been uploaded"; then
+              echo "Correctly failed to upload the same deb package again (overwrite=false)"
+          else
+              echo "Failed to fail the upload of the same deb package again (overwrite=false)"
+              exit 1
+          fi
+        
+      # Try to upload again the same deb package with overwrite=true, it should succeed
+      - name: (admin) Try to upload the same deb package again with overwrite=true
+        run: |
+          PACKAGE_NAME="${{ env.RANDOM }}-${HOSTNAME}-admin_nginx_1.26.0-1~bookworm_amd64.deb"
+
+          cp ${HOSTNAME}_nginx_1.26.0-1~bookworm_amd64.deb $PACKAGE_NAME
+          curl --fail-with-body -L --post301 -s -q -X POST -H "Authorization: Bearer ${{ secrets.API_TEST_ADMIN_API_KEY }}" -F "file=@${PACKAGE_NAME}" -F "overwrite=true" ${{ secrets.API_TEST_HOST }}/api/v2/snapshot/1/upload
+          if [ $? -ne 0 ]; then
+              echo "Failed to upload the same deb package again with overwrite=true"
               exit 1
           fi
 
@@ -138,11 +166,10 @@ jobs:
       # Generate a unique package name to avoid conflicts when multiple pipelines run at the same time
       - name: (test-user1) Try to upload a deb package with test-user1 API key
         run: |
-          RANDOM=$(date +%s)
-          PACKAGE_NAME="${RANDOM}-${HOSTNAME}-test-user1_nginx_1.26.0-1~bookworm_amd64.deb"
+          PACKAGE_NAME="${{ env.RANDOM }}-${HOSTNAME}-test-user1_nginx_1.26.0-1~bookworm_amd64.deb"
 
           cp ${HOSTNAME}_nginx_1.26.0-1~bookworm_amd64.deb $PACKAGE_NAME
-          OUTPUT=$(curl --fail-with-body -L --post301 -s -q -X POST -H "Authorization: Bearer ${{ secrets.API_TEST_TEST_USER1_API_KEY }}" -F "files=@${PACKAGE_NAME}" ${{ secrets.API_TEST_HOST }}/api/v2/snapshot/3/upload) || true
+          OUTPUT=$(curl --fail-with-body -L --post301 -s -q -X POST -H "Authorization: Bearer ${{ secrets.API_TEST_TEST_USER1_API_KEY }}" -F "file=@${PACKAGE_NAME}" ${{ secrets.API_TEST_HOST }}/api/v2/snapshot/3/upload) || true
     
           if echo "$OUTPUT" | grep -q "You are not allowed to upload packages"; then
               echo "Correctly failed to upload deb package with test-user1 API key"
@@ -153,13 +180,12 @@ jobs:
 
       # Upload a rpm package using the test-user1 API key
       # Generate a unique package name to avoid conflicts when multiple pipelines run at the same time
-      - name: (test-user1) Try to upload an rpm package with test-user1 API key
+      - name: (test-user1) Try to upload a rpm package with test-user1 API key
         run: |
-          RANDOM=$(date +%s)
-          PACKAGE_NAME="${RANDOM}-${HOSTNAME}-test-user1_nginx-1.26.0-1.el7.ngx.x86_64.rpm"
+          PACKAGE_NAME="${{ env.RANDOM }}-${HOSTNAME}-test-user1_nginx-1.26.0-1.el7.ngx.x86_64.rpm"
   
           cp ${HOSTNAME}_nginx-1.26.0-1.el7.ngx.x86_64.rpm $PACKAGE_NAME
-          OUTPUT=$(curl --fail-with-body -L --post301 -s -q -X POST -H "Authorization: Bearer ${{ secrets.API_TEST_TEST_USER1_API_KEY }}" -F "files=@${PACKAGE_NAME}" ${{ secrets.API_TEST_HOST }}/api/v2/snapshot/4/upload) || true
+          OUTPUT=$(curl --fail-with-body -L --post301 -s -q -X POST -H "Authorization: Bearer ${{ secrets.API_TEST_TEST_USER1_API_KEY }}" -F "file=@${PACKAGE_NAME}" ${{ secrets.API_TEST_HOST }}/api/v2/snapshot/4/upload) || true
     
           if echo "$OUTPUT" | grep -q "You are not allowed to upload packages"; then
               echo "Correctly failed to upload deb package with test-user1 API key"
@@ -200,11 +226,10 @@ jobs:
       # Generate a unique package name to avoid conflicts when multiple pipelines run at the same time
       - name: (test-user2) Try to upload a deb package with test-user2 API key
         run: |
-          RANDOM=$(date +%s)
-          PACKAGE_NAME="${RANDOM}-${HOSTNAME}-test-user2_nginx_1.26.0-1~bookworm_amd64.deb"
+          PACKAGE_NAME="${{ env.RANDOM }}-${HOSTNAME}-test-user2_nginx_1.26.0-1~bookworm_amd64.deb"
 
           cp ${HOSTNAME}_nginx_1.26.0-1~bookworm_amd64.deb $PACKAGE_NAME
-          curl --fail-with-body -L --post301 -s -q -X POST -H "Authorization: Bearer ${{ secrets.API_TEST_TEST_USER2_API_KEY }}" -F "files=@${PACKAGE_NAME}" ${{ secrets.API_TEST_HOST }}/api/v2/snapshot/5/upload
+          curl --fail-with-body -L --post301 -s -q -X POST -H "Authorization: Bearer ${{ secrets.API_TEST_TEST_USER2_API_KEY }}" -F "file=@${PACKAGE_NAME}" ${{ secrets.API_TEST_HOST }}/api/v2/snapshot/5/upload
           if [ $? -ne 0 ]; then
               echo "Failed to upload deb package"
               exit 1
@@ -212,13 +237,12 @@ jobs:
 
       # Upload a rpm package using the test-user2 API key
       # Generate a unique package name to avoid conflicts when multiple pipelines run at the same time
-      - name: (test-user2) Try to upload an rpm package with test-user2 API key
+      - name: (test-user2) Try to upload a rpm package with test-user2 API key
         run: |
-          RANDOM=$(date +%s)
-          PACKAGE_NAME="${RANDOM}-${HOSTNAME}-test-user2_nginx-1.26.0-1.el7.ngx.x86_64.rpm"
+          PACKAGE_NAME="${{ env.RANDOM }}-${HOSTNAME}-test-user2_nginx-1.26.0-1.el7.ngx.x86_64.rpm"
   
           cp ${HOSTNAME}_nginx-1.26.0-1.el7.ngx.x86_64.rpm $PACKAGE_NAME
-          curl --fail-with-body -L --post301 -s -q -X POST -H "Authorization: Bearer ${{ secrets.API_TEST_TEST_USER2_API_KEY }}" -F "files=@${PACKAGE_NAME}" ${{ secrets.API_TEST_HOST }}/api/v2/snapshot/6/upload
+          curl --fail-with-body -L --post301 -s -q -X POST -H "Authorization: Bearer ${{ secrets.API_TEST_TEST_USER2_API_KEY }}" -F "file=@${PACKAGE_NAME}" ${{ secrets.API_TEST_HOST }}/api/v2/snapshot/6/upload
           if [ $? -ne 0 ]; then
               echo "Failed to upload rpm package"
               exit 1
